# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_OpenCV:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Echo current dir
      run: pwd
    
    - name: Unzip OpenCV
      run: ls -la && unzip opencv-4.6.0.zip
      working-directory: ./lib
    
    - name: Make Directory "build"
      run: mkdir build
      working-directory: ./lib/opencv-4.6.0

    - name: Run CMake
      run: cmake ..
      working-directory: ./lib/opencv-4.6.0/build
      
    - name: Build OpenCV
      run: make
      working-directory: ./lib/opencv-4.6.0/build
      
  build:
  
    runs-on: ubuntu-latest
    needs: [build_OpenCV]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
